export const JOURNAL_AUDIO_FOLDER_NAME = 'journal-recordings'
export const INTERVIEW_AUDIO_FOLDER_NAME = 'interview-recordings'
export const CHAT_AUDIO_FOLDER_NAME = 'chat-recordings'
export const ANSWER_FORM_AUDIO_FOLDER_NAME = 'add-answer-recordings'
export const CURATED_CUESTIONS_FOLDER_NAME = 'curated-questions'
