name: Check Code Quality

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile --ignore-scripts

    - name: Generate API code
      run: npm run api:generate

    - name: Check formatting
      run: npm run format:check

    - name: Check linting
      run: npm run lint:check

    - name: Check TypeScript
      run: npm run type:check
